In [1]:
import numpy as np

In [2]:
arr = np.array([0,0,0,0,0,1,1,1,1,1])
arr

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

# 특정 값의 개수 세기

In [3]:
np.where(arr==0, 1, 0).sum()

5

# 빈 배열에서 이어 붙이기

In [4]:
empty_arr = np.empty((0,11), np.float64)
empty_arr

array([], shape=(0, 11), dtype=float64)

In [5]:
print('arr size: ', empty_arr.size)
print('arr len: ', len(empty_arr))
print('arr shape: ', empty_arr.shape)

arr size:  0
arr len:  0
arr shape:  (0, 11)


In [6]:
empty_arr2 = np.empty((1,3), np.float64)
empty_arr2

array([[4.658208e-310, 0.000000e+000, 1.581010e-322]])

In [7]:
print('arr len:', len(empty_arr2))

arr len: 1


In [8]:
empty_arr2.ndim

2

In [9]:
empty_arr2 = np.append(empty_arr2, np.array([[1,3,4]]), axis=0)

In [10]:
empty_arr2

array([[4.658208e-310, 0.000000e+000, 1.581010e-322],
       [1.000000e+000, 3.000000e+000, 4.000000e+000]])

In [11]:
empty_arr2 = np.delete(empty_arr2, [0,0], axis=0)

In [12]:
empty_arr2

array([[1., 3., 4.]])

## column 이어 붙이기(병합)


In [13]:
a = np.array([[0,11],[1,12],[2,13],[3,14]],)

In [14]:
a

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14]])

In [15]:
a.shape

(4, 2)

In [16]:
b = a[:,0]

In [17]:
b = b.reshape(1,-1)

In [18]:
b.shape

(1, 4)

In [19]:
c = np.concatenate([a,b.T], axis=1)

In [20]:
c

array([[ 0, 11,  0],
       [ 1, 12,  1],
       [ 2, 13,  2],
       [ 3, 14,  3]])

In [21]:
d = np.concatenate([a,b.T], axis=1)

In [32]:
empty3 = np.empty((1,2), dtype=np.float64)

In [33]:
empty3

array([[0., 0.]])

In [34]:
empty3 = np.append(empty3, np.array([[1,2]], dtype=np.float64), axis=0)

In [35]:
empty3

array([[0., 0.],
       [1., 2.]])

In [36]:
empty3 = np.append(empty3, np.array([[3,4]], dtype=np.float64), axis=0)

In [37]:
empty3

array([[0., 0.],
       [1., 2.],
       [3., 4.]])

In [29]:
empty3 = np.delete(empty3, [0], axis=0)

In [30]:
empty3

array([[[1., 2.],
        [3., 4.],
        [5., 6.]]])

In [31]:
empty3.shape

(1, 3, 2)